App.WebStore/Models/Dados.cs
namespace App.WebStore.Models
{
    public class Dados
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Nota { get; set; }
        public decimal Valor { get; set; }
        public string Periodo { get; set; }
        public string NotaAlunos { get; set; }
        public string Tipo { get; set; }
        public string Duracao { get; set; }
        public string Comentarios { get; set; }
        public string Curso { get; set; }
    }
}

App.WebStore/Models/Examplo.cs
namespace App.WebStore.Models
{
    public class Exemplo
    {
        public int Id { get; set; }
        public string Nome { get; set; }
    }
}

App.WebStore/Models/ModelStateExtension.cs
using System.Collections.Generic;
namespace App.WebStore.Models
{
    public static class ModelStateExtension
    {
        public static void AddModelError(this System.Web.Mvc.ModelStateDictionary modelStateDictionary, IDictionary<string, string> items)
        {
            if (items?.Count > 0)
            {
                foreach (var item in items)
                {
                    modelStateDictionary.AddModelError(item.Key, item.Value);
                }
            }
        }
    }
}

App.WebStore/Controllers/CategoriesController.cs
using App.WebStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Castle.Components.Validator;
using NHibernate.Criterion;
using App.WebStore.Models.ValidatorExtension;
namespace App.WebStore.Controllers
{
    public class CategoriesController : Controller
    {
        public IValidatorRunner Runner { get; set; }
        public CategoriesController()
        {
            Runner = new ValidatorRunner(new CachedValidationRegistry());
        }
        [HttpGet]
        public ActionResult Index()
        {
            IEnumerable<Category> categories = Category.FindAll(Order.Asc("Description")).ToList();
            return View(categories);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category model)
        {
            if (Runner.IsValid(model))
            {
                model.CreateAndFlush();
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(Runner.GetErrors(model));
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id.HasValue)
            {
                Category model = Category.TryFind(id);
                if (model != null)
                {
                    return View(model);
                }

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Category model)
        {
            if (Runner.IsValid(model))
            {
                Category local = Category.TryFind(model.Id);
                local.Description = model.Description;
                local.UpdateAndFlush();
                return RedirectToAction("Index");
            }
            ModelState.AddModelError(Runner.GetErrors(model));
            return View(model);
        }
    }
}

App.WebStore/Controllers/ExemploController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using App.WebStore.Models;

namespace App.WebStore.Controllers
{
    public class ExemploController : Controller
    {
        // GET: Exemplo
        public ActionResult Index()
        {
            //IList<Dados> dados = new List<Dados>();
            //dados.Add(new Dados
            //{
            //    Comentarios = "c",
            //    Duracao = "1",
            //    Id = 1, 
            //    Nome = "N",
            //    Nota    ="10",
            //    NotaAlunos = "9.5",
            //    Periodo = "Integral",
            //    Tipo = "Tipo A",
            //    Valor = 250
            //});
            //dados.Add(new Dados
            //{
            //    Comentarios = "b",
            //    Duracao = "2",
            //    Id = 2,
            //    Nome = "A",
            //    Nota = "9",
            //    NotaAlunos = "8.9",
            //    Periodo = "Matutino",
            //    Tipo = "Tipo B",
            //    Valor = 185.58M
            //});
            return View();
        }

        [OutputCache(Duration = 600)]
        public PartialViewResult IndexPartial()
        {
            IList<Dados> dados = new List<Dados>();
            dados.Add(new Dados
            {
                Comentarios = "c",
                Duracao = "1",
                Id = 1,
                Nome = "N",
                Nota = "10",
                NotaAlunos = "9.5",
                Periodo = "Integral",
                Tipo = "Tipo A",
                Valor = 250
            });
            dados.Add(new Dados
            {
                Comentarios = "b",
                Duracao = "2",
                Id = 2,
                Nome = "A",
                Nota = "9",
                NotaAlunos = "8.9",
                Periodo = "Matutino",
                Tipo = "Tipo B",
                Valor = 185.58M
            });
            return PartialView("_PartialPageExemplo", dados);
        }

        [HttpPost]
        public ActionResult Resgatar(IEnumerable<int> Ids)
        {
            if (Ids == null) throw new ArgumentNullException(nameof(Ids));
            return View();
        }
    }
}

App.WebStore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace App.WebStore.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

App.WebStore/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using App.WebStore.Models;

namespace App.WebStore.Controllers
{
    public class ProductsController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
            var order = NHibernate.Criterion.Order.Asc("Description");
            return View(Product.FindAll(order));
        }

        [HttpGet]
        public ActionResult Create()
        {
            RenderViewBag();
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product model, long categoryId)
        {
            model.Category = Category.TryFind(categoryId);
            model.CreateAndFlush();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(long? id)
        {
            if (id.HasValue)
            {
                Product model = Product.TryFind(id.Value);
                if (model != null)
                {
                    RenderViewBag(model?.Category?.Id);
                    return View(model);
                }

            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(Product model, long categoryId)
        {
            model.Category = Category.TryFind(categoryId);
            model.UpdateAndFlush();
            return RedirectToAction("Index");
        }

        protected void RenderViewBag(long? selectValue = null)
        {
            var order = NHibernate.Criterion.Order.Asc("Description");
            IEnumerable<Category> items = Category.FindAll(order);
            ViewBag.CategoryId = new SelectList(items, "Id", "Description", selectValue);
        }
    }
}

App.WebStore/Views/Categories/Create.cshtml
@model App.WebStore.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App.WebStore/Views/Categories/Edit.cshtml
@model App.WebStore.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App.WebStore/Views/Categories/Index.cshtml
@model IEnumerable<App.WebStore.Models.Category>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayName("Quantidade")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

App.WebStore/Views/Exemplo/Create.cshtml
@model App.WebStore.Models.Exemplo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Examplo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Selecao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Selecao)
                    @Html.ValidationMessageFor(model => model.Selecao, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App.WebStore/Views/Exemplo/Index.cshtml
@model IEnumerable<App.WebStore.Models.Dados>
@{ ViewBag.Title = "Index"; }

@Html.Action("IndexPartial")

@*@using (Html.BeginForm("Resgatar", "Exemplo", FormMethod.Post))
{
    <table class="table">
        <tr>
            <td>
                @Html.Display("Selecionar")
            </td>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="checkbox" name="Ids" value="@item.Id" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }
        <tr>
            <td colspan="4">
                <button type="submit" class="btn btn-primary">Alterar</button>
            </td>
        </tr>
    </table>
}*@

App.WebStore/Views/Exemplo/_PartialPageExemplo.cshtml
@model IEnumerable<App.WebStore.Models.Dados>

@foreach (var m in Model)
{
    <hr class="separador" />
    <div class="container">
        <a href="#" class="dp1 d3 m3 s3">
            <div>@m.Nome</div>
        </a> <!-- Campo do NOme da facuade ex: Fmu -->
        <a href="#" class="dp1 d3 m3 s3">
            <div>@m.Curso</div>
        </a><!-- Compo do nome do curso EX: Analise e desenvolvimento de sistemas -->
        <div class="dp1 d3 m3 s3">@m.NotaAlunos</div><!-- Campo da nota do mec EX:3-->
    </div>
    <div class="container">
        <div class="dp1 d3 m3 s3">@m.Valor</div><!-- Preço do curso EX: R$250,00-->
        <div class="dp1 d3 m3 s3">@m.Periodo</div><!-- período do curso ex: matutino -->
        <div class="dp1 d3 m3 s3">@m.Nota</div><!-- Nota que o aluno da para o curso e facudade Ex: curso nota 7 , Facul nota 3 -->
    </div>
    <div class="container">
        <div class="dp1 d3 m3 s3">@m.Tipo</div><!-- Tipo do curso ex: Presencial, semi-Presencial, Ead -->
        <div class="dp1 d3 m3 s3">@m.Duracao</div><!-- Duração do curso EX: 5 semetres -->
        <a href="#" class="dp1 d3 m3 s3">
            <div>@m.Comentarios</div>
        </a><!-- Comentos dos alunos sobre o curso e/ou facuade -->
    </div>
    <hr />
}

App.WebStore/Views/Products/Create.cshtml
@model App.WebStore.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("CategoryId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Category.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App.WebStore/Views/Products/Edit.cshtml
@model App.WebStore.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("CategoryId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Category.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

App.WebStore/Views/Products/Index.cshtml
@model IEnumerable<App.WebStore.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.Description)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Description)
        </td>
        <td>
            @if (item != null)
            {
                <text>@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id=item.Id })</text>
            }
 
        </td>
    </tr>
}

</table>

App.WebStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Products", "Index", "Products")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>